// This Jenkinsfile assumes you are familiar with the use of the library as
// presented in the build/Jenkinsfile example file.
@Library('ecdc-pipeline')
import ecdcpipeline.ImageBuilder

// Disable concurrent builds to avoid overwritting images in the registry.
properties([
  [$class: 'JiraProjectProperty'],
  disableConcurrentBuilds(abortPrevious: true)
])

// imageVersion should be updated when changes are made to the Dockerfile. It
// is assumed that the Jenkins node has already authenticated with the
// container registry.
imageVersion = '1.2.3'
imageName = "dockerregistry.esss.dk/ecdc_group/build-node-images/custom-build-node:${imageVersion}"

// ImageBuilder will append "-dev" to the version if the branch is not
// "master", and "-pr" if the build is due to a pull request. These versions
// of the image can be overwritten, but overwriting is not allowed when
// building the "master" branch.
imageBuilder = new ImageBuilder(this, imageName)
imageBuilder.buildAndPush()
